"""Setup name field to unique.

Revision ID: 672e9acb9286
Revises: ba9359cdf4c9
Create Date: 2025-08-21 09:36:01.243620

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "672e9acb9286"
down_revision: Union[str, Sequence[str], None] = "ba9359cdf4c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "tasks", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tasks", type_="unique")
    # ### end Alembic commands ###
